version: '3.7'

services:
  # vault:
  #   ports:
  #     - 8200:8200
  #   environment:
  #     - VAULT_DEV_ROOT_TOKEN_ID=secret

  # smtp-server:
  #   ports:
  #     - 8025:8025
  #     - 1025:1025

  background-jobs:
   restart: unless-stopped
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__background_jobs_sagas=Server=sqlserver;Database=master;User Id=sa;Password=P@ssw0rd;Trusted_Connection=False; MultipleActiveResultSets=true;
     - MessageBus__TransportType=RabbitMQ
     - MessageBus__RabbitMQ__Url=amqp://rabbitmq
     - MessageBus__AzureSB__ConnectionString=<config>
     # At every 5th minute
     - Jobs__ProducerScanningSchedule=* * * * *
     - Jobs__ProducerScanningEnabled=true
     - Services__PersonalDataService__GrpcUrl=http://personal-api:15003
     - Services__PersonalDataService__Url=http://personal-api:5003
     - Logging__Seq__Url=http://seq/
     - Logging__Seq__ApiKey=${SEQ_KEY:-}
     - Logging__Seq__Enabled=false
     - Metrics__Enabled=false